import assert from 'node:assert/strict';
import * as THREE from 'three';
import {prepareExportScene,prepareIntegratedLoft} from './export-scene.mjs';
import {prepareLoftExport} from './export-loft.mjs';
import {readFileSync} from 'node:fs';
const root=new THREE.Group();root.position.set(10,2,7);
const material=new THREE.MeshStandardMaterial({color:'#b8b2a7'});
material.envMap=new THREE.Texture();
const instances=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),material,2);
instances.setMatrixAt(0,new THREE.Matrix4().makeTranslation(1,.5,0));
instances.setMatrixAt(1,new THREE.Matrix4().makeTranslation(3,.5,0));
root.add(instances);
assert.throws(()=>prepareExportScene(THREE,[{name:'house',object:root},{name:'duplicate',object:root}],[0,0,0]),/duplicate|overlap/i,'A source root cannot be exported twice');
assert.throws(()=>prepareExportScene(THREE,[{name:'house',object:root},{name:'nested',object:instances}],[0,0,0]),/duplicate|overlap/i,'A child already owned by the house cannot also be a separate export root');
assert.throws(()=>prepareExportScene(THREE,[{name:'nested',object:instances},{name:'house',object:root}],[0,0,0]),/duplicate|overlap/i,'Root overlap detection is independent of input order');
const hidden=new THREE.Mesh(new THREE.BoxGeometry(20,20,20),material);hidden.visible=false;root.add(hidden);
const result=prepareExportScene(THREE,[{name:'house',object:root}],[10,2,7]);
assert.equal(result.manifest.meshes,2);
const bounds=new THREE.Box3().setFromObject(result.scene);
assert.deepEqual(bounds.min.toArray(),[.5,0,-.5]);
assert.deepEqual(bounds.max.toArray(),[3.5,1,.5]);
result.scene.traverse(o=>{assert(!o.isInstancedMesh);if(o.isMesh)assert.equal(o.material.envMap,null);});
assert(material.envMap,'Export must not change the source material');
assert.deepEqual(prepareExportScene(THREE,[{name:'house',object:root}],[10,2,7]).manifest,result.manifest);
console.log('Export preserves metre scale, transforms, instances and source materials; hidden meshes are excluded');
const integrated={root:new THREE.Group(),loft:{root:new THREE.Group()}};
integrated.loft.root.userData.furnishedLoft=true;
integrated.root.add(integrated.loft.root);
for(const key of ['floor','furniture','int','ceiling']){
  const group=new THREE.Group();group.visible=false;
  group.add(new THREE.Mesh(new THREE.BoxGeometry(1,1,1),material));
  integrated.loft[key]=group;integrated.loft.root.add(group);
}
integrated.loft.walls={N:new THREE.Group()};
integrated.loft.walls.N.add(new THREE.Mesh(new THREE.BoxGeometry(1,1,1),material));
integrated.loft.root.add(integrated.loft.walls.N);
assert.deepEqual(prepareIntegratedLoft(integrated),{floor:1,furniture:1,int:1,ceiling:1,walls:1});
assert(['floor','furniture','int','ceiling'].every(key=>integrated.loft[key].visible));
assert.throws(()=>prepareIntegratedLoft({root:new THREE.Group(),loft:integrated.loft}),/descendant|belong|under|attach/i,'A separate loft cannot masquerade as part of the house');
integrated.loft.root.userData.furnishedLoft=false;
assert.throws(()=>prepareIntegratedLoft(integrated),/furnished|integrated/i);
integrated.loft.root.userData.furnishedLoft=true;
integrated.loft.root.remove(integrated.loft.floor);
assert.throws(()=>prepareIntegratedLoft(integrated),/descendant|belong|under|attach/i,'Detached floor geometry cannot count as exported coverage');
integrated.loft.root.add(integrated.loft.floor);
integrated.loft.floor.clear();
assert.throws(()=>prepareIntegratedLoft(integrated),/floor|empty|coverage/i,'A marked but incomplete loft cannot pass ownership validation');
const loftRoot=new THREE.Group();loftRoot.position.set(10.48,0,7.18);loftRoot.visible=false;
const floor=new THREE.Mesh(new THREE.BoxGeometry(2,.1,2),material);floor.position.set(7,2.67,15);loftRoot.add(floor);
const flue=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),material);flue.name='Loft room details_structure_flue';loftRoot.add(flue);
const window=new THREE.Group();window.name='opening_gable_0';window.add(new THREE.Mesh(new THREE.BoxGeometry(1,1,1),material));loftRoot.add(window);
const loftExport=prepareLoftExport(THREE,{root:loftRoot,dims:{originPlot:{x:10.48,z:7.18}}});
assert.equal(loftExport.manifest.meshes,1,'Supplement excludes existing house chimney and gable window');
assert.equal(loftExport.manifest.sourceMeshes,1);
assert.deepEqual(loftExport.manifest.sourceOrigin,[10.48,2.465,7.18]);
assert(Math.abs(new THREE.Box3().setFromObject(loftExport.scene).max.y-2.72)<1e-6,'Loft remains at 2.72 m above house floor');
assert.equal(loftRoot.visible,false);assert.equal(flue.visible,true);assert.equal(window.visible,true);
assert.deepEqual(loftRoot.position.toArray(),[10.48,0,7.18],'Source placement and visibility remain unchanged');
const nested=new THREE.Group(),hiddenParent=new THREE.Group();hiddenParent.visible=false;
hiddenParent.add(new THREE.Mesh(new THREE.BoxGeometry(1,1,1),material));nested.add(hiddenParent);loftRoot.add(nested);
assert.throws(()=>prepareLoftExport(THREE,{root:loftRoot,dims:{originPlot:{x:10.48,z:7.18}}}),/omitted source meshes/,'Hidden descendants cannot silently disappear from a complete loft export');
const route=JSON.parse(readFileSync(new URL('./walkthrough-route.json',import.meta.url)));
assert.equal(route.shots.reduce((sum,shot)=>sum+shot.duration,0),120);
assert.equal(route.shots.length,22);
for(const shot of route.shots)for(const key of ['start','end','targetStart','targetEnd'])assert(shot[key].length===3&&shot[key].every(Number.isFinite));
console.log('Separate loft export preserves alignment and source state; 120-second route verified');
